version: '3.9'

services:
  postgres:
    container_name: graphql_postgres_container
    image: postgres:bullseye
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${MYSQL_DATABASE:-blog}
    networks:
      - database
    ports:
      - "15432:5432"
    restart: always

networks:
  database:
    driver: bridge

volumes:
  postgres:
