graphql:
  packages:
    - org.example
    - io.github.wickedev.graphql
    - org.springframework.security.core.userdetails.UserDetails
  voyager:
    enabled: true
  graphiql:
    enabled: true

graphiql:
  enabled: true

server:
  port: 8080

spring:
  application:
    name: blog
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:15432/blog
    username: admin
    password: admin

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    org.springframework.data.r2dbc: DEBUG

auth:
  jwt:
    issuer: graphql-practice-issuer

r2dbc:
  migrate:
    resourcesPath: classpath:/db/migration/*.sql


