graphql:
  packages:
    - org.example
server:
  port: 8081

spring:
  application:
    name: blog
  r2dbc:
    url: r2dbc:mariadb://127.0.0.1:13306/blog
    username: admin
    password: admin

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

auth:
  jwt:
    issuer: graphql-practice-issuer
