graphql:
  packages:
    - org.example
  federation:
    enabled: true
    tracing:
      enabled: true
  voyager:
    enabled: true

server:
  port: 8080

spring:
  application:
    name: blog
  r2dbc:
    url: r2dbc:mariadb://127.0.0.1:13306/blog
    username: admin
    password: admin

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    org.springframework.data.r2dbc: DEBUG

auth:
  jwt:
    issuer: graphql-practice-issuer

r2dbc:
  migrate:
    resourcesPath: classpath:/db/migration/*.sql


